### ISSUE TITLE
[chore] Import css files, enhance reset.css and organize assets

### ISSUE THREAD

**Issue by ghost** [jsh1147/codeit-FE10-Fandom-K#16]
## 📝 Description
- css 파일 연결과 reset.css 보완 및 리소스 정리

## ✅ To-Do List

- [x] global, reset, variables.css main.jsx에 import하기
- [x] reset.css 보완하기
- [x] assets 추가 및 제거하기
