### ISSUE TITLE
[feat] Add layout

### ISSUE THREAD

**Issue by jsh1147** [jsh1147/codeit-FE10-Fandom-K#2]
## 📝 Description

- 헤더가 필요한 페이지에 사용되는 레이아웃 개발

## ✅ To-Do List

- [x] 레이아웃 컴포넌트 개발
- [x] 헤더 컴포넌트 개발
- [x] 레이아웃 컴포넌트 라우팅에 적용
