### ISSUE TITLE
[feat] Implement landing page

### ISSUE THREAD

**Issue by jsh1147** [jsh1147/codeit-FE10-Fandom-K#20]
## 📝 Description

- 사이트에 처음 도달할 시 보여지는 랜딩 페이지 작성

## ✅ To-Do List

- [x] 페이지 구조 작성
- [x] 페이지 디자인 작성
- [x] 페이지 버튼 기능 구현
