### ISSUE TITLE
[refactor]Extract modal as common component

### ISSUE THREAD

**Issue by devmanta** [jsh1147/codeit-FE10-Fandom-K#23]
## 📝 Description

- 후원 모달 컴포넌트를 공통 컴포넌트 역할 할 수 있게끔 추상화 작업 진행

## ✅ To-Do List

- [x] 모달 컴포넌트 추상화
- [x] esc누르면 닫히고
- [x] 모달 열면 모달 내부의 포커스
- [x] 탭 빙빙돌리기
- [x] 모달 뒤에있는애 스크롤 안되게
- [x] 모달 닫기 애니메이션
