### ISSUE TITLE
[feat] Add global, reset, vars.css and assets

### ISSUE THREAD

**Issue by ghost** [jsh1147/codeit-FE10-Fandom-K#3]
## 📝 Description

- 공통 요소 css 파일 및 피그마 리소스 추가

## ✅ To-Do List

- [x] global.css 추가 
- [x] variables.css 추가
- [x] reset.css 추가
- [x] assets 구조화
- [x] 이미지 추가
- [x] 아이콘 추가
