### ISSUE TITLE
[feat] Add vote modal

### ISSUE THREAD

**Issue by ghost** [jsh1147/codeit-FE10-Fandom-K#38]
## 📝 Description

- 이달의 차트 내 차트 투표하기 모달 개발

## ✅ To-Do List

- [x] 모달 컴포넌트 생성
- [x] 모달 기능 추가
- [x] 모달 스타일
- [ ] 차트 리스트 & 차트 모달 내 득표수 천 단위 콤마 추가
