### ISSUE TITLE
[feat] Add credit api with localStorage

### ISSUE THREAD

**Issue by devmanta** [jsh1147/codeit-FE10-Fandom-K#4]
## 📝 Description

- 내 크레딧 조회/추가 공통사용 api 추가

## ✅ To-Do List

- [x] 로컬스토리지에 크레딧 값 저장하기
- [x] 로컬스토리지에서 크레딧 값 가져오기
- [x] 크레딧값 조회 api
- [x] 크레딧값 추가 api
