### ISSUE TITLE
[feat] Add Mypage 

### ISSUE THREAD

**Issue by duckjae12** [jsh1147/codeit-FE10-Fandom-K#46]
## 📝 Description

  - MyPage 구현 

## ✅ To-Do List

- [x] 컴포넌트 개발
- [x] 선택카드 체크표시 기능
- [x] 중복선택 기능
- [x] 추가하기 버튼 기능 
- [x] x버튼 삭제 기능
