### ISSUE TITLE
[refactor] Refactor assigned feature

### ISSUE THREAD

**Issue by jsh1147** [jsh1147/codeit-FE10-Fandom-K#52]
## 📝 Description

- R&R 할당 받은 기능에 대한 리팩토링

## ✅ To-Do List

- [x] 배경 방식 통일
- [x] 콘텐츠 스크롤 시 그라데이션 적용 
- [x] 상호작용에 따른 애니메이션 적용
- [x] 기타 수정(명칭 변경, 파일 분리 등)
