### ISSUE TITLE
[refactor] Additional refactoring on assigned feature

### ISSUE THREAD

**Issue by jsh1147** [jsh1147/codeit-FE10-Fandom-K#62]
## 📝 Description

- R&R 할당 받은 기능에 대한 추가적인 리팩토링

## ✅ To-Do List

- [x] 버튼 컴포넌트 CSS 개선
- [x] 모달 컴포넌트 적용
- [x] 버튼 동작 시 토스트 생성
- [x] 오픈그래프 적용
