### ISSUE TITLE
[refactor] Modify modal logic and data reload

### ISSUE THREAD

**Issue by devmanta** [jsh1147/codeit-FE10-Fandom-K#66]
## 📝 Description

- 모달, 데이터 새로고침 관련 리팩토링

## ✅ To-Do List

- [x] 모달 백스크롤 커스텀훅 말고 modal component로 빼기
- [x] 모바일뷰에서 max-width 추가
- [x] 데이터 새로고침 할때 해당 데이터만 새로고침 되게 수정
