### ISSUE TITLE
[feat] Add styling for modal and chart details

### ISSUE THREAD

**Issue by ghost** [jsh1147/codeit-FE10-Fandom-K#68]
## 📝 Description

- 피드백 및 멘토링 사항 개발

## ✅ To-Do List
추가
- [x] 모바일 모달 레이아웃 수정
- [x] 모달 인풋 라디오 컬러 추가
- [x] 모달 인풋 acitve 스타일 추가
- [x] 모달 성공 토스트 추가
- [x] 스크롤 스타일링
- [x] 스웨거 데이터 추가

피드백
- [x] myCredit > credit 변경
